using System.Text.Json;
using FinControl.Transactions.Core.Context;
using FinControl.Transactions.Core.Domain;
using FinControl.SharedKernel.Domain.Events;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace FinControl.Transactions.Core.Features.Commands.RegisterTransaction;

public class RegisterTransactionCommandHandler(
    TransactionsDbContext db,
    ILogger<RegisterTransactionCommandHandler> logger)
{
    private const string Exchange = "transactions.events";
    private const string RoutingKey = "transaction.created";
    private static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web);

    public async Task<RegisterTransactionResponse> Handle(
        RegisterTransactionCommand command,
        CancellationToken cancellationToken = default)
    {
        var existing = await CheckIdempotencyAsync(command.IdempotencyKey, cancellationToken);
        if (existing is not null)
            return MapToResponse(existing);

        Transaction transaction = new()
        {
            Category = command.Category,
            Amount = command.Amount,
            Description = command.Description,
            TransactionDate = command.TransactionDate == default ? DateTimeOffset.UtcNow : command.TransactionDate,
            IdempotencyKey = command.IdempotencyKey,
            CreatedAt = DateTimeOffset.UtcNow,
            CreatedBy = command.UserId,
            CreatedByName = command.UserName,
            CreatedByEmail = command.UserEmail
        };

        // Explicit transaction to ensure atomicity between transaction and outbox.
        // InMemoryDatabase does not support real transactions; IsRelational() prevents the exception in tests.
        var useTransaction = db.Database.IsRelational();
        var tx = useTransaction ? await db.Database.BeginTransactionAsync(cancellationToken) : null;
        try
        {
            // 1st write: persists the transaction and gets Id + NavigationId generated by the database
            db.Set<Transaction>().Add(transaction);
            await db.SaveChangesAsync(cancellationToken);

            // 2nd write: persists the outbox with complete payload (Id and NavigationId already populated)
            var @event = MapToEvent(transaction, command);
            db.Set<OutboxMessage>().Add(new OutboxMessage
            {
                MessageType = nameof(TransactionRegisteredMessage),
                Payload = JsonSerializer.Serialize(@event, JsonOptions),
                Exchange = Exchange,
                RoutingKey = RoutingKey,
                CreatedAt = DateTimeOffset.UtcNow
            });
            await db.SaveChangesAsync(cancellationToken);

            if (tx is not null)
                await tx.CommitAsync(cancellationToken);
        }
        catch
        {
            if (tx is not null)
                await tx.RollbackAsync(cancellationToken);
            throw;
        }
        finally
        {
            if (tx is not null)
                await tx.DisposeAsync();
        }

        if (logger.IsEnabled(LogLevel.Information))
            logger.LogInformation(
                "Transaction registered queued in outbox | Exchange={Exchange} RoutingKey={RoutingKey} TransactionId={TransactionId} NavigationId={NavigationId} Amount={Amount} CorrelationId={CorrelationId}",
                Exchange, RoutingKey,
                transaction.Id, transaction.NavigationId, transaction.Amount, command.CorrelationId);

        return MapToResponse(transaction);
    }

    private Task<Transaction?> CheckIdempotencyAsync(
        Guid idempotencyKey,
        CancellationToken cancellationToken) =>
        db.Transactions
            .AsNoTracking()
            .FirstOrDefaultAsync(l => l.IdempotencyKey == idempotencyKey, cancellationToken);

    private static RegisterTransactionResponse MapToResponse(Transaction transaction) =>
        new(
            NavigationId: transaction.NavigationId ?? Guid.NewGuid(),
            CreatedAt: transaction.CreatedAt
        );

    private static TransactionRegisteredMessage MapToEvent(
        Transaction transaction,
        RegisterTransactionCommand command) =>
        new(
            Id: transaction.Id,
            NavigationId: transaction.NavigationId ?? Guid.NewGuid(),
            Category: (EventTransactionCategory)(int)transaction.Category,
            Amount: transaction.Amount,
            Description: transaction.Description,
            TransactionDate: transaction.TransactionDate,
            OccurredAt: transaction.CreatedAt,
            UserId: command.UserId,
            UserName: command.UserName,
            UserEmail: command.UserEmail,
            CorrelationId: command.CorrelationId
        );
}
