namespace FinControl.Infrastructure.Vault;

/// <summary>
/// HashiCorp Vault configurations read from appsettings / environment variables.
/// Expected section: "Vault"
/// </summary>
public sealed class VaultOptions
{
    public const string SectionName = "Vault";

    /// <summary>Vault server address. Ex: https://vault.company.com:8200</summary>
    public string Address { get; init; } = "http://localhost:8200";

    /// <summary>
    /// Authentication method: "AppRole" (production) | "Token" (local dev).
    /// </summary>
    public string AuthMethod { get; init; } = "AppRole";

    // ── AppRole (production) ──────────────────────────────────────────────────
    /// <summary>RoleId generated by Vault for the application (AppRole).</summary>
    public string? RoleId { get; init; }

    /// <summary>
    /// SecretId generated by Vault for the application (AppRole).
    /// In production, comes from environment variable or Kubernetes volume — NEVER commit here.
    /// </summary>
    public string? SecretId { get; init; }

    // ── Token (local development) ───────────────────────────────────────
    /// <summary>Root token for exclusive use in local development.</summary>
    public string? Token { get; init; }

    // ── Secret paths ───────────────────────────────────────────────────
    /// <summary>
    /// List of KV (v2) paths whose values will be injected into IConfiguration.
    /// Ex: ["fincontrol/lancamentos", "fincontrol/shared"]
    /// </summary>
    public string[] SecretPaths { get; init; } = [];

    /// <summary>Mount point of the KV secrets engine. Vault default: "secret".</summary>
    public string MountPoint { get; init; } = "secret";

    /// <summary>
    /// Prefix added to keys injected into IConfiguration.
    /// Leave empty ("") to inject secrets directly at the root of IConfiguration,
    /// allowing transparent access via standard keys (ex: "ConnectionStrings:DefaultConnection").
    /// </summary>
    public string ConfigurationPrefix { get; init; } = "";

    /// <summary>If true, failures reading Vault throw an exception during initialization.</summary>
    public bool Required { get; init; } = true;
}
